openapi: 3.0.0
info:
  title: maps
  version: '1.0'
  contact:
    email: test@dev.com
  description: 地図API
servers:
  - url: 'http://localhost:8080'
paths:
  /api/maps/deg2name:
    get:
      summary: '方位角を12方位名に変換'
      tags:
        - maps
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: 処理結果
                  name:
                    type: string
                    description: 12方位名
              examples:
                example:
                  value:
                    status: true
                    name: 'E'
      operationId: get-api-maps-deg2name
      description: 方位角を12方位名に変換
      parameters:
        - schema:
            type: number
            minimum: 0
            maximum: 360
            default: 90
            format: float
          in: query
          name: deg
          required: true
          description: 方位の角度
    parameters: []
  /api/maps/tky2jgdg:
    get:
      summary: '日本測地系を世界測地系に変換（1次式）'
      tags:
        - maps
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: 処理結果
                  lat:
                    type: number
                    description: 十進緯度（世界測地系）
                  lon:
                    type: number
                    description: 十進経度（世界測地系）
              examples:
                example:
                  value:
                    status: true
                    lat: 35.68078249647387
                    lon: 139.7672349196828
      operationId: get-api-maps-tky2jgdg
      description: 日本測地系を世界測地系に変換（1次式）
      parameters:
        - schema:
            type: number
            default: 35.67755556
            format: double
          in: query
          name: lat
          required: true
          description: 十進緯度（日本測地系）
        - schema:
            type: number
            default: 139.7704444
            format: double
          in: query
          name: lon
          required: true
          description: 十進経度（日本測地系）
    parameters: []
  /api/maps/jgd2tkyg:
    get:
      summary: '世界測地系を日本測地系に変換（1次式）'
      tags:
        - maps
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: 処理結果
                  lat:
                    type: number
                    description: 十進緯度（日本測地系）
                  lon:
                    type: number
                    description: 十進経度（日本測地系）
              examples:
                example:
                  value:
                    status: true
                    lat: 35.67755561088216
                    lon: 139.77044447609083
      operationId: get-api-maps-jgd2tkyg
      description: 世界測地系を日本測地系に変換（1次式）
      parameters:
        - schema:
            type: number
            default: 35.68078249
            format: double
          in: query
          name: lat
          required: true
          description: 十進緯度（世界測地系）
        - schema:
            type: number
            default: 139.767235
            format: double
          in: query
          name: lon
          required: true
          description: 十進経度（世界測地系）
    parameters: []
  /api/maps/distancet:
    get:
      summary: '２地点間の距離（球面三角法）'
      tags:
        - maps
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: 処理結果
                  distance:
                    type: number
                    description: 距離（cm）
              examples:
                example:
                  value:
                    status: true
                    distance: 27335.473262593438
      operationId: get-api-maps-distancet
      description: ２地点間の距離（球面三角法）
      parameters:
        - schema:
            type: number
            format: double
            default: 35.689753
          in: query
          name: lat1
          required: true
          description: 十進緯度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 139.691731
          in: query
          name: lon1
          required: true
          description: 十進経度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 35.447495
          in: query
          name: lat2
          required: true
          description: 十進緯度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 139.6424
          in: query
          name: lon2
          required: true
          description: 十進経度（世界測地系[GSR80]）
    parameters: []
  /api/maps/distanceh:
    get:
      summary: '２地点間の距離（ヒュベニ）'
      tags:
        - maps
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: 処理結果
                  distance:
                    type: number
                    description: 距離（cm）
              examples:
                example:
                  value:
                    status: true
                    distance: 27248.24567995688
      operationId: get-api-maps-distanceh
      description: ２地点間の距離（ヒュベニ）
      parameters:
        - schema:
            type: number
            format: double
            default: 35.689753
          in: query
          name: lat1
          required: true
          description: 十進緯度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 139.691731
          in: query
          name: lon1
          required: true
          description: 十進経度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 35.447495
          in: query
          name: lat2
          required: true
          description: 十進緯度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 139.6424
          in: query
          name: lon2
          required: true
          description: 十進経度（世界測地系[GSR80]）
    parameters: []
  /api/maps/distances:
    get:
      summary: '２地点間の距離（測地線航海算法）'
      tags:
        - maps
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: 処理結果
                  distance:
                    type: number
                    description: 距離（cm）
              examples:
                example:
                  value:
                    status: true
                    distance: 32204.322252668517
      operationId: get-api-maps-distances
      description: ２地点間の距離（測地線航海算法）
      parameters:
        - schema:
            type: number
            format: double
            default: 35.689753
          in: query
          name: lat1
          required: true
          description: 十進緯度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 139.691731
          in: query
          name: lon1
          required: true
          description: 十進経度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 35.447495
          in: query
          name: lat2
          required: true
          description: 十進緯度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 139.6424
          in: query
          name: lon2
          required: true
          description: 十進経度（世界測地系[GSR80]）
    parameters: []
  /api/maps/distanceto:
    get:
      summary: '角度・距離から緯度経度を取得'
      tags:
        - maps
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: 処理結果
                  lat:
                    type: number
                    description: 十進緯度（世界測地系[GSR80]）
                  lon:
                    type: number
                    description: 十進経度（世界測地系[GSR80]）
              examples:
                example:
                  value:
                    status: true
                    lat: 43.06473675180286
                    lon: 141.3469832298937
      operationId: get-api-maps-distanceto
      description: 角度・距離から緯度経度を取得
      parameters:
        - schema:
            type: number
            format: double
            default: 35.689753
          in: query
          name: lat
          required: true
          description: 十進緯度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 139.691731
          in: query
          name: lon
          required: true
          description: 十進経度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 9.362103972638495
          in: query
          name: a
          required: true
          description: 角度
        - schema:
            type: number
            format: double
            default: 831070.2256498174
          in: query
          name: len
          required: true
          description: 距離（m）
    parameters: []
  /api/maps/direction:
    get:
      summary: '２地点間の角度'
      tags:
        - maps
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: 処理結果
                  a:
                    type: number
                    description: 角度
              examples:
                example:
                  value:
                    status: true
                    a: 9.362103972638495
      operationId: get-api-maps-direction
      description: ２地点間の角度
      parameters:
        - schema:
            type: number
            format: double
            default: 35.689753
          in: query
          name: lat1
          required: true
          description: 十進緯度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 139.691731
          in: query
          name: lon1
          required: true
          description: 十進経度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 43.064301
          in: query
          name: lat2
          required: true
          description: 十進緯度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 141.346874
          in: query
          name: lon2
          required: true
          description: 十進経度（世界測地系[GSR80]）
    parameters: []
  /api/maps/tile:
    get:
      summary: '緯度経度・ズームレベルからタイル座標を取得'
      tags:
        - maps
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    description: 処理結果
                  x:
                    type: number
                    description: タイル座標X
                  y:
                    type: number
                    description: タイル座標Y
                  z:
                    type: number
                    description: ズームレベル
                  px_x:
                    type: number
                    description: タイル左上からY値[pixel]
                  px_y:
                    type: number
                    description: タイル左上からX値[pixel]
              examples:
                example:
                  value:
                    status: true
                    x: 14505
                    y: 6469
                    z: 14
                    px_x: 162
                    px_y: 148
      operationId: get-api-maps-tile
      description: 緯度経度・ズームレベルからタイル座標を取得
      parameters:
        - schema:
            type: number
            format: double
            default: 35.360771305
          in: query
          name: lat
          required: true
          description: 十進緯度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 138.7273035
          in: query
          name: lon
          required: true
          description: 十進経度（世界測地系[GSR80]）
        - schema:
            type: number
            format: double
            default: 14
          in: query
          name: z
          required: true
          description: ズームレベル
    parameters: []
tags:
  - name: maps
    description: ''
components:
  schemas: {}
  securitySchemes: {}
